### YamlMime:ManagedReference
# Only generate docs for Emulator and BasicInputProvider, and only show methods and properties (for now)
apiRules:
- include:
    uidRegex: '^UnityHawk\.Emulator$'
- exclude:
    uidRegex: '^UnityHawk\.Emulator.#ctor$' # exclude constructor
- include:
    uidRegex: '^UnityHawk\.Emulator\..*'
    type: Method
- include:
    uidRegex: '^UnityHawk\.Emulator\..*'
    type: Property
- include:
    uidRegex: '^UnityHawk\.Emulator\..*'
    type: Type

- include:
    uidRegex: '^UnityHawk\.BasicInputProvider$'
- include:
    uidRegex: '^UnityHawk\.BasicInputProvider\..*'
- include:
    uidRegex: '^UnityHawk\.InputProvider$'
- include:
    uidRegex: '^UnityHawk\.InputProvider\..*'
- include:
    uidRegex: '^UnityHawk\.InputEvent$'
- include:
    uidRegex: '^UnityHawk\.InputEvent\..*'
- exclude:
    uidRegex: '.*'